server:
  port: 8762

spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blackPeysen/eureka-config.git
          search-paths: springcloud
          username: blackPeysen
          password: Pmm1363039590!
          basedir: E:\workSpace\springcloud\eureka-config\config\
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#此处与2.0之前配置不同，配置路径改变，暴露接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
