server:
  port: 8675

spring:
  application:
    name: eureka-goods
  jpa:
    show-sql: true
  datasource:
    username: envision
    password: envision
    # 2.0 需设置时区参数serverTimezone=GMT
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&useSSL=true&createDatabaseIfNotExist=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
