eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false  #关闭自我保护机制，生产环境建议打开
  client:
    service-url:
      #注册中心
      defaultZone: http://${eureka.instance.hostname}:8673/eureka/,http://${eureka.instance.hostname}:8671/eureka/
    register-with-eureka: false   #使用将注册中心注册成服务
    fetch-registry: false

spring:
  application:
    name: eureka-server
